#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT_DIR"

MODE="offline"
if [[ "${1:-}" == "--live" ]]; then
  MODE="live"
fi

TRACE_DIR="proof/traces/latest"
rm -rf "$TRACE_DIR"
mkdir -p "$TRACE_DIR"

echo "🚀 Pata Proof Pack Demo"
echo "Mode: $MODE"
echo "Output directory: $TRACE_DIR"
echo

run_case() {
  local case_name="$1"
  local persona="$2"

  local input_file="proof/inputs/${case_name}.goal"
  local fixture_file="proof/fixtures/${case_name}.json"
  local raw_out="$TRACE_DIR/${case_name}.raw.json"
  local md_out="$TRACE_DIR/${case_name}.trace.md"

  local goal
  goal="$(cat "$input_file")"

  if [[ "$MODE" == "live" ]]; then
    if cargo run -q -p cli -- --persona "$persona" --goal "$goal" --config config/app.toml > "$raw_out"; then
      :
    else
      echo "⚠️ Live execution failed for $case_name; using fixture fallback."
      cp "$fixture_file" "$raw_out"
    fi
  else
    cp "$fixture_file" "$raw_out"
  fi

  python3 - "$raw_out" "$md_out" "$case_name" <<'PY'
import json
import sys
from pathlib import Path

src = Path(sys.argv[1])
out = Path(sys.argv[2])
case_name = sys.argv[3]
payload = json.loads(src.read_text())

answer = payload.get("answer", "")
sections = {
    "ANALYSIS": "",
    "HYPOTHESIS": "",
    "ACTION_PLAN": "",
    "VALIDATION": "",
    "DURABLE_RULES_CHECK": "",
    "FINAL_ANSWER": "",
}
for line in answer.splitlines():
    for key in sections:
        prefix = f"{key}:"
        if line.strip().startswith(prefix):
            sections[key] = line.strip()[len(prefix):].strip()

structured = payload.get("structured_output") or {}
trace = structured.get("execution_trace") or {}
events = trace.get("events") or []

lines = []
lines.append(f"# Proof Trace — {case_name}")
lines.append("")
lines.append("## Input")
lines.append(f"- Persona: `{payload.get('persona', 'unknown')}`")
lines.append(f"- Goal: {payload.get('goal', 'n/a')}")
lines.append("")
lines.append("## ReAct-style Reasoning Summary")
for key in ["ANALYSIS", "HYPOTHESIS", "ACTION_PLAN", "VALIDATION", "DURABLE_RULES_CHECK", "FINAL_ANSWER"]:
    lines.append(f"- **{key}**: {sections[key] or '(not present as explicit line section)'}")
lines.append("")
lines.append("## Verification")
lines.append(f"- verification_status: `{structured.get('verification_status', 'n/a')}`")
lines.append(f"- confidence_level: `{structured.get('confidence_level', 'n/a')}`")
lines.append(f"- confidence: `{payload.get('confidence', 'n/a')}`")
failures = structured.get("global_failures") or []
lines.append(f"- global_failures_count: `{len(failures)}`")
if failures:
    for failure in failures:
        lines.append(f"  - {failure}")
lines.append("")
lines.append("## Observable Execution Trace")
lines.append(f"- run_id: `{trace.get('run_id', 'n/a')}`")
lines.append(f"- events_count: `{len(events)}`")
lines.append("")
for event in events:
    lines.append(f"{event.get('index', '?')}. **{event.get('event_type', '?')}** ({event.get('level', '?')}): {event.get('detail', '')}")

out.write_text("\n".join(lines) + "\n")
PY

  echo "✅ ${case_name}: $md_out"
}

run_case developer_code_review developer
run_case smb_support_ticket smb
run_case teacher_structured_tutoring teacher

cat > "$TRACE_DIR/README.md" <<'EOF2'
# Proof Pack Execution Artifacts

This folder is generated by `proof/run_demo.sh`.

- `*.raw.json`: raw agent payload (live output or deterministic fixture fallback)
- `*.trace.md`: human-readable proof traces

Open the trace markdown files in this folder to review the full demo storyline.
EOF2

echo

echo "🎯 Proof Pack ready. Open: $TRACE_DIR/README.md"
